### ISSUE TITLE
Add repo description

### ISSUE THREAD

**Issue by dandv** [googlesamples/android-SpeedTracker#5]
... so it shows up at https://github.com/googlesamples

**Comment by codingjeremy** [comment]
I'm confused, it has a description and shows up for me in /googlesamples/ when I search for it. Is it showing up for you now?

**Comment by dandv** [comment]
[Nope](https://github.com/googlesamples/android-SpeedTracker):

![image](https://cloud.githubusercontent.com/assets/33569/17953709/7d5b6c84-6a2a-11e6-9086-ce65b9f3200f.png)

**Comment by codingjeremy** [comment]
Thanks for the catch, it wasn't showing on a couple samples. It is now added.
