### ISSUE TITLE
Set applicationId in build.gradle

### ISSUE THREAD

**Issue by kbojarski** [googlesamples/android-SpeedTracker#7]
The application crashes on launch on phone when upgrading latest play services and support library versions (9.0.2 and 23.4.0) because the build.gradle file does not have an Application id

`Process: com.example.android.wearable.speedtracker, PID: 29484
                                                                                           java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.`

`applicationId 'com.example.android.wearable.speedtracker'` needs to be added to the android>defaultConfig portion of the file

**Comment by codingjeremy** [comment]
We upgraded to the latest version of the support library, please try again. I just tested on on 5.1.1 and it works.

It also looks like there is an issue with a Firebase API, like something needs to be added for it to work correctly. This sample doesn't actually use Firebase, so maybe you need to add an application id for that API somewhere in the manifest?

I am closing this but if you see the issue still, please reopen and let me know the version of Android you are using along with the Google Play Services version. Thanks!
