### ISSUE TITLE
Does this work as standalone?

### ISSUE THREAD

**Issue by fbcbl** [googlesamples/android-SpeedTracker#8]
Hey!

Just set this up with an LG G Urbane with Android Wear 2.0, but it only detects location if the phone location is on. Was this supposed to work using only the watch GPS?

Thanks.

**Comment by codingjeremy** [comment]
This is a Wear 1.0 app, so it is not meant for 2.0. I did try it with a device with GPS and it worked outdoors pretty quickly on Wear 2.0. 

The Urbane 2 has GPS, but if you have an Urbane 1, you are probably out of luck. Also, I believe the Urbane 2 doesn't have regional satellite stuff if you don't have SIM in it the first time you run it, so it needs to get that information from satellites and that first GPS boot up outside may take awhile (maybe 5-15 minutes?). Make sure you do it outside, just might take some time the first time. After that, it should be fast.
